La mavia/bsp build target clasifier
mapz-zpp/intellij-scala pull request #5
Opened 2023-11-27 20:40 UTC by LaMavia

[Bazel implementation](https://github.com/JetBrains/intellij-bazel/blob/989f93226725cb33e7520eb55a2a0b2b09ffcc98/src/main/kotlin/org/jetbrains/bazel/extension/BazelBuildTargetClassifier.kt#L5) for reference

2023-11-27 21:58 UTC, p-fuchs requested changes, later dismissed

2023-11-27 21:58 UTC, p-fuchs commented on scala/scala-impl/src/org/jetbrains/plugins/scala/lang/formatting/settings/ImportsPanel.java
> +        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), this.$$$getMessageFromBundle$$$("messages/ScalaBundle", "imports.panel.classes.to.use.only.with.prefix"),
We should remove this - it's junk added by IntelliJ

2023-11-27 21:58 UTC, p-fuchs commented on scala/scala-impl/src/org/jetbrains/plugins/scala/lang/formatting/settings/ImportsPanel.java
> +        panel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), this.$$$getMessageFromBundle$$$("messages/ScalaBundle", "imports.panel.import.layout"), TitledBorder.DEFA
Same here

2023-11-27 21:58 UTC, p-fuchs commented on scala/scala-impl/src/org/jetbrains/plugins/scala/lang/formatting/settings/ImportsPanel.java
> +        panel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), this.$$$getMessageFromBundle$$$("messages/ScalaBundle", "imports.panel.imports.always.marked.as.used"), T
And here

2023-11-27 21:58 UTC, p-fuchs commented on .idea/vcs.xml
That file should also be removed - added by intelliJ, not needed.

2023-11-28 12:07 UTC, LaMavia commented on scala/scala-impl/src/org/jetbrains/plugins/scala/lang/formatting/settings/ImportsPanel.java
> +        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), this.$$$getMessageFromBundle$$$("messages/ScalaBundle", "imports.panel.classes.to.use.only.with.prefix"),
Should be taken care of

2023-11-28 12:07 UTC, LaMavia commented on scala/scala-impl/src/org/jetbrains/plugins/scala/lang/formatting/settings/ImportsPanel.java
> +        panel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), this.$$$getMessageFromBundle$$$("messages/ScalaBundle", "imports.panel.import.layout"), TitledBorder.DEFA
Done

2023-11-28 12:07 UTC, LaMavia commented on scala/scala-impl/src/org/jetbrains/plugins/scala/lang/formatting/settings/ImportsPanel.java
> +        panel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), this.$$$getMessageFromBundle$$$("messages/ScalaBundle", "imports.panel.imports.always.marked.as.used"), T
And done

2023-11-28 12:08 UTC, LaMavia commented on .idea/vcs.xml
I've removed the file

2023-11-28 19:06 UTC, p-fuchs commented on .idea/vcs.xml
Hmmm, let's revert that change completely - just copy the file from `no-idea` branch and put it there.
Sorry, my bad, I didn't notice that it was present before.

2023-12-01 20:18 UTC, p-fuchs approved these changes

2023-12-01 20:20 UTC, merged