[Sbt over BSP] Extension points implementation
mapz-zpp/intellij-scala pull request #9
Opened 2023-12-05 16:21 UTC by p-fuchs

2023-12-05 16:23 UTC, p-fuchs commented on .idea/vcs.xml
We constantly have problems with this file changing - it should not be changed, but could we postpone fixing it until final merge?

2023-12-06 10:47 UTC, agluszak commented on .idea/vcs.xml
add .idea to .gitignore

2023-12-06 10:58 UTC, agluszak requested changes

2023-12-06 10:58 UTC, agluszak commented on scala/integration/intellij-bsp/resources/META-INF/scala-intellij-bsp-integration.xml
> +</idea-plugin>
add newline

2023-12-06 10:58 UTC, agluszak commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/config/ScalaBspProjectAwareExtension.scala
> +import java.util
file is not formatted

2023-12-06 10:58 UTC, agluszak commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/config/ScalaBspProjectAwareExtension.scala
> +import java.util
I'd suggest using import name mapping instead

`import java.util.{List => JavaList}`

2023-12-06 10:58 UTC, agluszak commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/extension/ScalaBuildTargetClassifier.scala
> +  private val sbtLabelRegex = """@?@?(?<repository>.*)//(?<package>.*):(?<target>.*)""".r
this looks like Bazel's labelling scheme, does it work for sbt too?

2023-12-06 10:58 UTC, agluszak commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/flow/open/ScalaBspDetailsConnectionGenerator.scala
> +  override def executeAndWait(list: util.List[String], virtualFile: VirtualFile, outputStream: OutputStream, project: Project): Unit = ???
these two are still not implemented

2023-12-06 10:58 UTC, agluszak commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/flow/open/ScalaBspDetailsConnectionGenerator.scala
> +    found
could you describe what it's supposed to do?

2023-12-06 10:58 UTC, agluszak commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/project/bsp/ScalaSdkGetter.scala
> +}
add newline

2023-12-06 23:08 UTC, AnthonyGrod commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/flow/open/ScalaBspDetailsConnectionGenerator.scala
> +    found
It's supposed to return a handle to a file pointed by the dependent `path`

2023-12-06 23:09 UTC, p-fuchs commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/extension/ScalaBuildTargetClassifier.scala
> +  private val sbtLabelRegex = """@?@?(?<repository>.*)//(?<package>.*):(?<target>.*)""".r
We should discuss at the tomorrow's meeting how this is presented in the UI to the user because right now we don't know what to look for.

2023-12-07 10:50 UTC, agluszak commented on scala/integration/intellij-bsp/src/org/jetbrains/plugins/scala/bsp/flow/open/ScalaBspDetailsConnectionGenerator.scala
> +  override def calculateImportWizardSteps(path: Path, observableMutableProperty: ObservableMutableProperty[ConnectionFileOrNewConnection]): util.List[ImportProjectWizardStep] = List.empty.asJava
nit: use JavaList here as well (unless there's a different convention in intellij-scala)

2023-12-18 16:32 UTC, jastice commented
The current PR is huge, it might be due to including changes that happened on the base branch. I think you need to rebase your own changes on 233.x

2023-12-18 18:19 UTC, agluszak commented
> The current PR is huge, it might be due to including changes that happened on the base branch. I think you need to rebase your own changes on 233.x

to be clear: what Justin meant was updating your base branch (`no-idea`) and *then* rebasing this PR on that updated one

2023-12-18 23:31 UTC, closed without merging